# Generated by Django 3.0.5 on 2020-04-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='relations',
            field=models.ManyToManyField(related_name='_entity_relations_+', through='common.Relation', to='common.Entity'),
        ),
    ]
