# Generated by Django 3.0.5 on 2020-04-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_entity_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='symbolSize',
            field=models.FloatField(default=40),
        ),
    ]
