# Generated by Django 3.0.5 on 2020-04-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_entity_relations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='relations',
        ),
    ]
