# Generated by Django 3.0.5 on 2020-04-15 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20200415_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='source',
            new_name='entity1',
        ),
        migrations.RenameField(
            model_name='relation',
            old_name='destination',
            new_name='entity2',
        ),
    ]
