# Generated by Django 3.0.5 on 2020-05-29 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_text'),
        ('register', '0002_big_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='big_user',
            name='fri_project',
            field=models.ManyToManyField(related_name='user_fri_pro', to='common.Project'),
        ),
        migrations.AddField(
            model_name='big_user',
            name='friend_apply',
            field=models.ManyToManyField(related_name='user_friend_app', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='big_user',
            name='project_invite',
            field=models.ManyToManyField(related_name='user_pro_inv', to='common.Project'),
        ),
        migrations.AlterField(
            model_name='big_user',
            name='friends',
            field=models.ManyToManyField(related_name='user_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
