# Generated by Django 3.0.5 on 2020-04-18 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200417_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Text',
        ),
    ]
