# Generated by Django 3.0.5 on 2020-05-20 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_reltype'),
        ('common', '0002_auto_20200511_2155'),
    ]

    operations = [
    ]
